<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>kf3tweaks</AssemblyName>
    <Description>Tweaks for Kemono Friends 3.</Description>
    <Version>0.9.1</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <Company>Team Pinewood</Company>
    <Authors>Team Pinewood</Authors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
    <PackageReference Include="BepInEx.Core" Version="5.*" />
    <PackageReference Include="BepInEx.PluginInfoProps" Version="1.*" />
    <PackageReference Include="UnityEngine.Modules" Version="2020.3.40.18644" IncludeAssets="compile" />
  </ItemGroup>
  
  <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
  </ItemGroup>
  
  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>lib\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="MMHOOK_Assembly-CSharp">
      <HintPath>lib\MMHOOK_Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="MonoMod.RuntimeDetour">
      <HintPath>lib\MonoMod.RuntimeDetour.dll</HintPath>
    </Reference>
    <Reference Include="MonoMod.Utils">
      <HintPath>lib\MonoMod.Utils.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>lib\UnityEngine.UI.dll</HintPath>
    </Reference>
  </ItemGroup>
  
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="copy /Y &quot;$(TargetDir)kf3tweaks.dll&quot; &quot;C:\Users\Usuario\KFP2G\BepInEx\plugins\kf3tweaks\kf3tweaks.dll&quot;" />
  </Target>
</Project>
